
import React from 'react';
import { RentRecord } from '../types';
import { Share2, Mail, MessageCircle, X, CheckCircle2, Download } from 'lucide-react';

interface Props {
  isOpen: boolean;
  onClose: () => void;
  record: RentRecord;
  tenantEmail?: string;
  tenantPhone?: string;
}

const ReceiptModal: React.FC<Props> = ({ isOpen, onClose, record, tenantEmail, tenantPhone }) => {
  if (!isOpen) return null;

  const receiptText = `RENT RECEIPT
--------------------------
Date: ${record.date}
Amount: ${record.amount.toLocaleString()} ${record.currency}
Tenant: ${record.tenantName}
Landlord: ${record.landlordName}
Method: ${record.paymentMethod}
Status: PAID
--------------------------
Generated by Kigali Rent Intel`;

  const handleWhatsApp = () => {
    if (!tenantPhone) return;
    const url = `https://wa.me/25${tenantPhone.replace(/\D/g, '')}?text=${encodeURIComponent(receiptText)}`;
    window.open(url, '_blank');
  };

  const handleEmail = () => {
    if (!tenantEmail) return;
    const subject = `Rent Receipt: ${record.date}`;
    const body = `Dear ${record.tenantName},\n\nPlease find your rent payment receipt details below:\n\n${receiptText}`;
    window.open(`mailto:${tenantEmail}?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`, '_blank');
  };

  return (
    <div className="fixed inset-0 bg-black/60 backdrop-blur-sm z-50 flex items-center justify-center p-4 animate-fade-in">
      <div className="bg-white rounded-xl shadow-2xl w-full max-w-sm overflow-hidden">
        
        {/* Success Header */}
        <div className="bg-green-600 p-6 text-center text-white">
          <div className="w-12 h-12 bg-white/20 rounded-full flex items-center justify-center mx-auto mb-3">
             <CheckCircle2 size={28} />
          </div>
          <h2 className="text-xl font-bold">Payment Recorded!</h2>
          <p className="text-green-100 text-sm">Receipt generated successfully.</p>
        </div>

        {/* Receipt Paper View */}
        <div className="p-6 bg-slate-50">
          <div className="bg-white p-6 shadow-sm border border-slate-200 rounded-lg relative overflow-hidden">
             {/* Decorative jagged bottom edge (css trick simulation) */}
             <div className="absolute top-0 left-0 w-full h-1 bg-gradient-to-r from-blue-500 to-indigo-500"></div>
             
             <div className="text-center mb-4">
                <h3 className="font-bold text-slate-800 uppercase tracking-widest text-sm">Rent Receipt</h3>
                <p className="text-[10px] text-slate-400 font-mono">{record.id.slice(0, 8).toUpperCase()}</p>
             </div>

             <div className="space-y-3 font-mono text-sm text-slate-600">
                <div className="flex justify-between border-b border-dashed border-slate-200 pb-2">
                   <span>Date:</span>
                   <span className="font-bold text-slate-800">{record.date}</span>
                </div>
                <div className="flex justify-between border-b border-dashed border-slate-200 pb-2">
                   <span>Tenant:</span>
                   <span className="font-bold text-slate-800">{record.tenantName}</span>
                </div>
                <div className="flex justify-between border-b border-dashed border-slate-200 pb-2">
                   <span>Method:</span>
                   <span>{record.paymentMethod}</span>
                </div>
                <div className="flex justify-between items-end pt-2">
                   <span className="font-bold">TOTAL</span>
                   <span className="text-xl font-bold text-slate-900">{record.amount.toLocaleString()} <span className="text-xs">RWF</span></span>
                </div>
             </div>
          </div>
        </div>

        {/* Actions */}
        <div className="p-4 space-y-3 bg-white border-t border-slate-100">
          <p className="text-center text-xs font-bold text-slate-400 uppercase mb-2">Send Receipt Via</p>
          
          <div className="grid grid-cols-2 gap-3">
            <button 
              onClick={handleWhatsApp}
              disabled={!tenantPhone}
              className="flex flex-col items-center justify-center gap-1 p-3 rounded-xl border border-slate-200 hover:bg-green-50 hover:border-green-200 hover:text-green-700 transition-all disabled:opacity-50 disabled:bg-slate-50"
            >
              <MessageCircle size={20} className={tenantPhone ? "text-green-600" : "text-slate-300"} />
              <span className="text-xs font-bold">WhatsApp</span>
            </button>

            <button 
              onClick={handleEmail}
              disabled={!tenantEmail}
              className="flex flex-col items-center justify-center gap-1 p-3 rounded-xl border border-slate-200 hover:bg-blue-50 hover:border-blue-200 hover:text-blue-700 transition-all disabled:opacity-50 disabled:bg-slate-50"
            >
              <Mail size={20} className={tenantEmail ? "text-blue-600" : "text-slate-300"} />
              <span className="text-xs font-bold">Email</span>
            </button>
          </div>

          <button onClick={onClose} className="w-full py-3 text-slate-500 font-medium text-sm hover:text-slate-800 transition-colors">
            Skip / Close
          </button>
        </div>
      </div>
    </div>
  );
};

export default ReceiptModal;
